camera_frame: camera_frame
charuco_frame: charuco_board
translation:
  x: 0.058
  y: -0.044
  z: 0.421
rotation:
  x: 0.980
  y: -0.029
  z: -0.045
  w: 0.190
euler_degrees:
  roll: 157.890
  pitch: 4.444
  yaw: -4.303





